DROP TABLE [Tracking]
DROP TABLE [OrderProduct]
DROP TABLE [OrderProductStatus]
DROP TABLE [Payment]
DROP TABLE [PaymentType]
DROP TABLE [Product]
DROP TABLE [AvailabilityStatus]
DROP TABLE [Order]
DROP TABLE [OrderStatus]
DROP TABLE [Delivery]
DROP TABLE [DeliveryStatus]
DROP TABLE [BusinessUser]
DROP TABLE [Business]
DROP TABLE [Category]
DROP TABLE [OperationalStatus]
DROP TABLE [UserAddress]
DROP TABLE [Address]
DROP TABLE [UserRole]
DROP TABLE [Role]
DROP TABLE [Users]
DROP TABLE [City]
DROP TABLE [Province]
DROP TABLE [Country]
DROP TABLE [ErrorTracer]


